import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


const marbleFont = localFont({
  src: [
    // Regular Styles
    { path: "../assets/fonts/marble/Marble Thin.woff", weight: "100", style: "normal" },
    { path: "../assets/fonts/marble/Marble ExtraLight.woff", weight: "200", style: "normal" },
    { path: "../assets/fonts/marble/Marble Light.woff", weight: "300", style: "normal" },
    { path: "../assets/fonts/marble/Marble Regular.woff", weight: "400", style: "normal" },
    { path: "../assets/fonts/marble/Marble Medium.woff", weight: "500", style: "normal" },
    { path: "../assets/fonts/marble/Marble SemiBold.woff", weight: "600", style: "normal" },
    { path: "../assets/fonts/marble/Marble Bold.woff", weight: "700", style: "normal" },
    { path: "../assets/fonts/marble/Marble ExtraBold.woff", weight: "800", style: "normal" },
    { path: "../assets/fonts/marble/Marble Black.woff", weight: "900", style: "normal" },

    // Italic Styles
    { path: "../assets/fonts/marble/Marble Thin Italic.woff", weight: "100", style: "italic" },
    { path: "../assets/fonts/marble/Marble ExtraLight Italic.woff", weight: "200", style: "italic" },
    { path: "../assets/fonts/marble/Marble Light Italic.woff", weight: "300", style: "italic" },
    { path: "../assets/fonts/marble/Marble Italic.woff", weight: "400", style: "italic" },
    { path: "../assets/fonts/marble/Marble Medium Italic.woff", weight: "500", style: "italic" },
    { path: "../assets/fonts/marble/Marble SemiBold Italic.woff", weight: "600", style: "italic" },
    { path: "../assets/fonts/marble/Marble Bold Italic.woff", weight: "700", style: "italic" },
    { path: "../assets/fonts/marble/Marble ExtraBold Italic.woff", weight: "800", style: "italic" },
    { path: "../assets/fonts/marble/Marble Black Italic.woff", weight: "900", style: "italic" },
  ],
  variable: "--font-marble",
  display: "swap",
});

const cottorwayFont = localFont({
  src: [
    {
      path: "../assets/fonts/cottorway/Cottorway Typeface Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/cottorway/Cottorway Typeface Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/cottorway/Cottorway Typeface Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/cottorway/Cottorway Typeface SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/cottorway/Cottorway Typeface Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/cottorway/Cottorway Typeface XtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-cottorway",
  display: "swap",
});

export const metadata: Metadata = {
  title: "AgriNex | Smart Farming & Agriculture Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${marbleFont.variable} ${cottorwayFont.variable} ${inter.className} min-h-full flex flex-col selection:bg-primary/40`}>
        {children}
      </body>
    </html>
  );
}